### ISSUE TITLE
Setup the API environment on Docker

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#1]
Since we plan to code next week, a Docker that standardize the development environment.

The Docker must support Django Rest and all the necessary tools to building the application API. @cjjcastro is the maintener and must specify what is needed

**Comment by cjjcastro** [comment]
was created a dockerfile and a docker-compose using python: 3-alpine as base and a django project was started to start the development

**Comment by cjjcastro** [comment]
this tutorial was used as a base: [Quickstart: Compose and Django](https://docs.docker.com/compose/django/)
