### ISSUE TITLE
Refactor - Isolate core formulas to estimate each score.

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#101]
## **Is your feature request related to a problem? Please describe.**
Actually, all the formulas to estimate each score are somewhere inside each component responsible. This makes complicated and hard to maintain. Some eventual change on formulas may occur and it will be not that simple.

## **Describe the solution you'd like**
To make it easy to find and change the formulas without messing up stuff, we need to isolate all the formulas on a single file. They'll be functions, which will receive the params and return the score. Those functions will be cast on each responsible component.

**Boolean scores doesn't need to be refactored!**

## **Describe alternatives you've considered**
Maybe, for some architectural detail, will not be possible to put all the formulas on a single file. If this is a reality, then create a single file for each formula, or maybe a file for each service on API. This surely is not the better option, cause make the maintenance not so easy as it could, but still better than it is today. The fewer files that are needed, the better.

## **Additional context**
To keep in track all the needed formulas, check the [Measurement Model](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/)

### Changes Required
- [ ] Remove all the formulas from the original file
- [ ] Create a file or few files to contain the formulas on functions
- [ ] Call the created functions on the responsible service

### Formulas
- [ ] Commit Quantity
- [ ] Pull Request Quality
- [ ] Contributors Quantity
- [ ] Issue Activity Rate
- [ ] Help Wanted Rate
- [ ] Good First Issue Rate

**Comment by Hiroshi18** [comment]
We cannot do that because the metrics are way too spaced

**Comment by Hiroshi18** [comment]
We will do that if we fix the metrics when we refactor the code
