### ISSUE TITLE
Feature - Measure Pull Request  quality

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#16]
**What is needed**
According to the [Measurement Model](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/), the API needs to measure PR quality. The way of measurement is defined by the document.

**Acceptance criteria**
- [x] Get the last 50 Pull Request of the repository
- [x] PRs older than 60 days must not be included
- [x] Classify each PR according to the document
- [x] Return a score based on PR quality mean

**Comment by Jacoapolinario** [comment]
I am doubtful on the second criterion. Could you help me?

**Comment by Jacoapolinario** [comment]
I am doubtful on the second criterion. Could you help me?

**Comment by Jacoapolinario** [comment]
I have doubts about the third criterion too

**Comment by filipetoyoshima** [comment]
The linked document was outdated. I've updated it with https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/

This document contains the necessary information to attend the requirements.

**Comment by filipetoyoshima** [comment]
> I am doubtful on the third criterion. Could you help me?

The linked document, at [metric #2](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/#m2-qualidade-de-aceitacao-de-pull-requests) contains a table which explains the rules for rating each PR.

> I have doubts about the fourth criterion too

After rating each PR as the document requires, the API must return a mean of all valid rated PRs, that is, the mean score of the last 50 PRs that are not older than 60 days.

**Comment by Hiroshi18** [comment]
We used a web crawler to get the comments on the every pr because of the limit of requests

**Comment by filipetoyoshima** [comment]
> We used a web crawler to get the comments on the every pr because of the limit of requests

It will do the job for now, but it has to be fixed before production.
