### ISSUE TITLE
Feature - Measure "Help Wanted" Issue Rate

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#19]
**What is needed**
According to the [Measurement Model](https://fga-eps-mds.github.io/2019.1-hubcare-docs/project-quality-management/measurement-model/), the API needs to measure the "Help Wanted" Issue Rate.

This Rate is obtained by dividing the number of open issues tagged with "Help Wanted" by the total open issues.

**Acceptance criteria**
- [x] Get all open issues
- [x] Count the number of issues tagged with "Help Wanted"
- [x] Consider "Help Wanted" aliases, as "help-wanted"
- [x] Return the obtained rate

**Comment by Jacoapolinario** [comment]
The total number of issues returned, and the total number of issues with Help wanted

**Comment by Jacoapolinario** [comment]
only the tests are done correctly.

**Comment by Jacoapolinario** [comment]
I'm having a hard time creating tests. can you help me?

**Comment by Jacoapolinario** [comment]
the only thing that is missing to close the issue and the PR is the test of that issue.

**Comment by cjjcastro** [comment]
as your api makes requests from an external api you need to create a mock to not directly access the external api

**Comment by cjjcastro** [comment]
look at this test as an example: https://github.com/fga-eps-mds/2019.1-hubcare-api/blob/devel/community/tests/test_license.py

**Comment by cjjcastro** [comment]
with this method I simulate the behavior of the requests.get that is used to request the external api

```
def mocked_requests_get(*args, **kwargs):
    '''
    This method will be used by the mock to replace requests.get
    '''
    class MockResponse:
        '''
        define response to mock request
        '''
        def __init__(self, json_data, status_code):
            self.json_data = json_data
            self.status_code = status_code

        def json(self):
            '''
            return all datas in object
            '''
            return self.json_data

    if args[0] == 'https://api.github.com/repos/test/repo_test':
        return MockResponse({"license": "value1"}, 200)
    elif args[0] == 'https://api.github.com/repos/test/no_license':
        return MockResponse({"license": None}, 200)
    elif args[0] == 'https://api.github.com/repos/test/old_license':
        return MockResponse({"license": "value1"}, 200)
    elif args[0] == 'https://api.github.com/repos/test/old_license_false':
        return MockResponse({"license": None}, 200)

    return MockResponse(None, 404)
```

**Comment by cjjcastro** [comment]
each url within the if and one url option expected by the test

```
if args[0] == 'https://api.github.com/repos/test/repo_test':
```

**Comment by cjjcastro** [comment]
to test and very simple, just show to your method that you will use mock in the test. like this
```
@mock.patch('community.views.license_view.requests.get', side_effect=mocked_requests_get)
```

then write the test normally as in the example below

```
@mock.patch('community.views.license_view.requests.get',
                side_effect=mocked_requests_get)
    def test_repository_not_existence(self, mock_get):
        '''
        test if not exist repository in github api
        '''
        request = self.factory.get('/community/license/cleber/desenho')
        response = LicenseView.as_view()(request, 'cleber', 'desenho')
        self.assertEqual(response.status_code, 404)

```

**Comment by cjjcastro** [comment]
As the team is very difficult with the tests we will postpone the tests of the application and enable the team to do so.
Then, since the issue already meets the criteria of acceptance, it can finish the task
