### ISSUE TITLE
Feature - Check the existence of Contribution Guide

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#21]
**What is needed**
According to the [Measurement Model](https://fga-eps-mds.github.io/2019.1-hubcare-docs/project-quality-management/measurement-model/), the API needs to check if the contribution guide exists.

**Acceptance criteria**
- [ ] Return if the Contribuition Guide exists

**Comment by VitorMeirelesOliveira** [comment]
I've a problem with database, please check the branch #21.
After build is ok, but then after 'make up', I've got the following problem:
"
django.db.migrations.exceptions.NodeNotFoundError: Migration pull_requests.0002_delete_pullrequesttemplate dependencies reference nonexistent parent node ('pull_requests', '0001_initial')
"
I already have deleted the migrations' files as you can see at the rapo and deleted the dbFile. as well.
Waiting a answer ASAP...

**Comment by cjjcastro** [comment]
I could not reproduce your error, run ```make build``` and make sure the error persists

**Comment by cjjcastro** [comment]
I found an error in your url and already fixed it
