### ISSUE TITLE
Feature - Check the existence of a License

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#25]
**What is needed**
According to the [Measurement Model](https://fga-eps-mds.github.io/2019.1-hubcare-docs/project-quality-management/measurement-model/), the API needs to check if the received repository is licensed.

**Acceptance criteria**
- [x] Return if the repository is licensed

**Comment by Hiroshi18** [comment]
test

**Comment by Jacoapolinario** [comment]
how do I put the parameters in the url?

**Comment by Brian2397** [comment]
How do I test to see if the requisitions are correct?

**Comment by Hiroshi18** [comment]
You can receive it in the method and use it or define it for the class and use the init

**Comment by Hiroshi18** [comment]
Use the requests factory it can simulate the requisitions

**Comment by Hiroshi18** [comment]
Here there is more about function https://www.codementor.io/kaushikpal/user-defined-functions-in-python-8s7wyc8k2

**Comment by Hiroshi18** [comment]
and here about testing https://stackoverflow.com/questions/10277748/how-to-get-request-object-in-django-unit-testing

**Comment by Brian2397** [comment]
How do you run the test in the terminal?

**Comment by Hiroshi18** [comment]
use docker-compose exec hubcareapi python manage.py test
remember that the container must be up

**Comment by cjjcastro** [comment]
we create within the community app a model that keeps if the repository has license, and in the view we order from the api of github.

**Comment by cjjcastro** [comment]
all code has been tested
