### ISSUE TITLE
Feature - Check the existence of Condute Code

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#26]
**What is needed**
According to the [Measurement Model](https://fga-eps-mds.github.io/2019.1-hubcare-docs/project-quality-management/measurement-model/), the API needs to check if the Condute Code exists.

**Acceptance criteria**
- [ ] Return if the Condute Code exists

**Comment by FranciscoHeronildo** [comment]
I'm having trouble verifying the date
![dificuldade](https://user-images.githubusercontent.com/30841230/56367557-d9b0aa80-61cb-11e9-9ae8-1e47ded9ce5f.png)

**Comment by filipetoyoshima** [comment]
Please, give a better description of your doubt and provide the code that is not working as you wanted, specifying in which part it's breaking.

**Comment by FranciscoHeronildo** [comment]
Problem solved
