### ISSUE TITLE
Feature - Check the existence of the repository Description

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#27]
**What is needed**
According to the [Measurement Model](https://fga-eps-mds.github.io/2019.1-hubcare-docs/project-quality-management/measurement-model/), the API needs to check if the Repository has a Description.

**Acceptance criteria**
- [x] Return if the repository has a Description

**Comment by Hiroshi18** [comment]
test
