### ISSUE TITLE
Feature - Check if the repository gives support to the users

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#47]
**Is your feature request related to a problem? Please describe.**

The user needs to have a rapid view of support that the repository may provide to the software's users.

**Describe the solution you'd like**

The API must provide, through an endpoint, a number between 0 and 1 which rate the support provided by the repository. The number must follow the **Question 3** in the [Measurement Model](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/)

**Acceptance Criteria**

- [ ] The weight of the received metrics described in the Measurement Model may change along time. To avoid magic numbers along the code and easy the maintenance, the weight values for each metric to this question must be obtained from an external file.

- [ ] The API must have an endpoint that provided the desired number

**Comment by FranciscoHeronildo** [comment]
Was the primary APP created?

**Comment by FranciscoHeronildo** [comment]
If not created, open a PR and put the main APP please.

**Comment by cjjcastro** [comment]
I already opened the pull request with these settings

**Comment by filipetoyoshima** [comment]
> I already opened the pull request with these settings

And it was just closed!

**Comment by Brian2397** [comment]
We finish the issue today(monday), but we did not get the issue activity rate

**Comment by filipetoyoshima** [comment]
Okay, you may let this issue on standby and proceed to solve another one. As soon as the issue activity rate is ready, we continue working on that.
