### ISSUE TITLE
Feature - Check if the repository is active

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#49]
**Is your feature request related to a problem? Please describe.**

The user needs to have a rapid view that shows if the repository is alive or abandoned.

**Describe the solution you'd like**

The API must provide, through an endpoint, a number between 0 and 1 which rate the activity level of the repository. The number must follow the **Question 1** in the [Measurement Model](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/)

**Acceptance Criteria**

- [ ] The weight of the received metrics described in the Measurement Model may change along time. To avoid magic numbers along the code and easy the maintenance, the weight values for each metric to this question must be obtained from an external file.

- [ ] The API must have an endpoint that provided the desired number

**Comment by Brian2397** [comment]
We can´t request the Last Month Commits, the Sum of commits is always 0.

**Comment by Brian2397** [comment]
The micro service don´t provide the last month Commits, but the last week commits

**Comment by FranciscoHeronildo** [comment]
We finished the issue today (Tuesday), but we did not get the active Issues rate and pull request quality
