### ISSUE TITLE
Authenticate every request made on GitHub API

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#61]
**Describe the bug**
Actually, our API uses just the free access of GitHub API, which is not even enough to testing.

We need to use some token to make the requests. For now, it may be done through a local env or local file that contains the dev's token. It's just a "temporary workaround", trust me :)

Please, write in the Pull Request description the procedure to authenticate properly

**Comment by Hiroshi18** [comment]
To use this you must use
```
export USERNAME='username'
export TOKEN='token'
```

**Comment by Hiroshi18** [comment]
I also changed the logic for the pr quality from the web scrapper to api
