### ISSUE TITLE
Feature - New service to check repositories

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#82]
## **Is your feature request related to a problem? Please describe.**
Actually, all services must check the existence of the repository's info on the database. It causes unnecessary processing labor on each service. 

## **Describe the solution you'd like**
To avoid this repetitive processing on each service, a new service must be created to validate the existence of this data on the database. Not only, but it must avoid any unnecessary access to the calculation services.

## **Describe alternatives you've considered**
Another option is to use the Gateway Service to do those checks, but we believe that it will cause overprocessing on a unique service.

## **Additional context**
Any information about actual architecture can be found in [Architecture Document](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/architecture-document/)

## Acceptation Criteria
- [x] Must be created a new service.
- [x] The new service must check the existence of a repo's data on Database and when the last modification was done.
- [x] The [Architecture Document](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/architecture-document/) must be updated

**Comment by filipetoyoshima** [comment]
Awaiting for @cjjcastro update [Architecture Document](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/architecture-document/), so it can be closed.

**Comment by cjjcastro** [comment]
already updated the architecture document, I inserted the new service in the diagrams

**Comment by filipetoyoshima** [comment]
Checked!
