### ISSUE TITLE
Set "Repository" service on Docker

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#86]
**Setup Details**

#82 defines a new service on API, but don't specify a Docker setting. It can make things difficult when executing the app.

To solve this, it is necessary to **set up the 'Repository' service on Docker**. Thus, `docker-compose up` should up this service on `localhost:8005`.

Another demand is to set up all the necessary updates on Deploy, in DigitalOcean. It includes the setting to DNS. As said by @cjjcastro, using `repository.hubcare.ml` as a new domain may be a good idea. Then it is necessary to enter the URL of the service in the environment variables of the API Gateway.

---

**Role**

- [ ] Scrum Master
- [x] DevOps
- [ ] Architect
- [ ] Product Manager

**Comment by cjjcastro** [comment]
another thing that needs to be done is the configuration of this service in DigitalOcean deploy, and the DNS configuration for this service, I suggest creating 'repository.hubcare.ml' as the domain. Then it is necessary to enter the URL of the service in the environment variables of the API gateway.

**Comment by filipetoyoshima** [comment]
> another thing that needs to be done is the configuration of this service in DigitalOcean deploy, and the DNS configuration for this service, I suggest creating 'repository.hubcare.ml' as the domain. Then it is necessary to enter the URL of the service in the environment variables of the API gateway.

Added to the issue description
