### ISSUE TITLE
Refactor - Contributors API service by Web Crawler

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#89]
## **Is your feature request related to a problem? Please describe.**
The contributor's service actual logic needs to check all commits from the last month and check who and the contributors. This is slow and uses a lot of requests... A LOT.

## **Describe the solution you'd like**
A possible solution is to use a web crawler to check GitHub's Insights page, where we can check the top commiters from the last month. As we don't need to know how many commits a contributor has, but only the number of contributors, it will do the work.

## **Describe alternatives you've considered**
The team didn't find some GitHub API endpoint who is responsible to retrieve such data, but if, on the issue resolution, a new and useful endpoint has been found, use it may be a solution.

**Comment by Hiroshi18** [comment]
The data is showed with js, so using requests in not possible.

**Comment by Hiroshi18** [comment]
There are workarounds but they involve adding another lib to the project like Selenium or phantomJS

**Comment by filipetoyoshima** [comment]
Well, although include a new dependency on the project isn't the best option, I believe it's a small price to get the required data in an efficient way.

**Comment by filipetoyoshima** [comment]
What do @cjjcastro and @RomuloSouza think about it?

**Comment by cjjcastro** [comment]
I do not like the idea of inserting more dependencies and I do not think it's necessary, probably the data you need is available in the api. There are many options in the api using 'Search'.
