### ISSUE TITLE
Refactor - Pull Request Service

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#90]
## **Is your feature request related to a problem? Please describe.**
There are some problems that will be solved by a refactorization:
- Pull Request takes too much time to respond.
- Manutenability is not ok.
- The endpoint must return a more complete report with the number of PRs that fits in each category of [PR metric](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/#m2-qualidade-de-aceitacao-de-pull-requests)

## **Describe the solution you'd like**
I really don't care how you gonna do that, solve the problems will guarantee a good solution.

## Additional Context
To evaluate the static quality of the new code, we will use Code Climate.

## Acceptance Criteria.
- [x] Take less time to load PR quality. How much? I really dunno. Less than it takes now.
- [x] Have no significant issues about the PR service on Code Climate.
- [x] Return a report with the number of PRs on each category.

**Comment by Hiroshi18** [comment]
Corrente we are using the Github api to make requests for the last 50 pr.

There are a few ways that we can optimize it first by reducing the number of requests or by changing the way we make them it's possible to use a web crawler in the GitHub website to get them or change the logic some other way.

**Comment by Hiroshi18** [comment]
But is necessary to test if it will be better or not using web crawler

Good luck (^^)/

**Comment by RomuloSouza** [comment]
Ok! I'm going to check that ^^

**Comment by RomuloSouza** [comment]
The github endpoint that returns the comments in PR doesn't return the comments in approvals and request changes reviews. What should I do? Do you think it's ok not to get them? @filipetoyoshima  @cjjcastro @Hiroshi18

**Comment by filipetoyoshima** [comment]
With comments in approvals, you mean like this?
![image](https://user-images.githubusercontent.com/29482983/58518120-47b19f80-8184-11e9-8bfd-92c4b51c8bb2.png)
