### ISSUE TITLE
Refactor - Return a complete report on gateway

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#94]
## **Is your feature request related to a problem? Please describe.**
The [Plugin](https://github.com/fga-eps-mds/2019.1-hubcare-plugin) needs to show a complete report with all the values of each metric. Some even need values of processed data and raw value.

**Not only this** but the API needs also to return the maximum value of each metric to reach the maximum score. For example, 10 commits at last 30 days set the max score, this data must be retrieved by gateway endpoint.

## **Additional context**
That information was defined by the [prototype](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project/prototype/). All the charts that will be rendered by the Plugin are defined there.

All this data is already computed, just need to be shown.

### Retrieved Data

- [x] Row with 10 values with the number of commits. Each cell with the value of a week in the last 10 from today.
- [x] Commits in last 4 weeks, in absolute number
- [x] 10 as the maximum number of commits to reaching a high score
- [ ] Number of different contributors, in absolute number.
- [ ] 6 as the maximum number of contributors to reaching a high score. (The prototype says 4, but actually, it is 6)
- [x] Number of active issues
- [x] Number of forgotten issues
- [x] Rate of active / total issues
- [x] Rate of Issues labeled with "good first issues"
- [x] 0.04 as the maximum rate of "good first issues" to reaching a high score
- [x] Rate of Issues labeled with "help wanted"
- [x] 0.04 as the maximum rate of "help wanted" issues to reaching a high score
- [x] Row with 7 values, one for each category of PR defined in the [measurement model](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/)
- [x] Bool value of the existence of READ.me
- [x] Bool value of the existence of Contribution Guide
- [x] Bool value of the existence of recent Release Notes
- [x] Bool value of the existence of a License
- [x] Bool value of the existence of a Code of Conduct
- [x] Bool value of the existence of at least one Issue Template
- [x] Bool value of the existence of Description
- [x] Bool value of the existence of at least one PR Template

**Comment by filipetoyoshima** [comment]
@Hiroshi18 is almost done with this. I believe it is better to wait for him and merge his branch on yours.

**Comment by RomuloSouza** [comment]
Do you think it's really a good idea to put the tooltips content in the backend? Why don't we just put this on plugin? @filipetoyoshima @cjjcastro @Hiroshi18

**Comment by filipetoyoshima** [comment]
Hmm... It makes sense to me. I think you're right.

**Comment by cjjcastro** [comment]
As it is a static data it does not make much sense to be in the api, this would only increase the dependency of the plugin with api

**Comment by Hiroshi18** [comment]
@cjjcastro I agree

**Comment by filipetoyoshima** [comment]
Fixed!

**Comment by RomuloSouza** [comment]
I would prefer to use the last 4 weeks of commits instead of the commits in the last 30 days. The metric we get comes per week, and 4 weeks is aproximately equals 30 days. May I just use this?

**Comment by filipetoyoshima** [comment]
Yep, there is no problem. I'll refer this on an issue to update the [Measurement Model](https://cjjcastro.gitlab.io/2019-1-hubcare-docs/project-quality-management/measurement-model/).

**Comment by filipetoyoshima** [comment]
Issue description fixed!
